### ISSUE TITLE
issue accessing zugferd.org

### ISSUE THREAD

**Issue by ousia** [ZUGFeRD/ZUGFeRD.github.io#3]
Hi there,

if you own the domain zugferd.org, would you please add a [custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)? for this?

As far as I can remember, a `CNAME` file with the contents `www.zugferd.org` in the root directory of this repository is all you may need.

Many thanks for your work providing ZUGFeRD information.

**Comment by jstaerk** [comment]
Hi,

thanks actually most of the info is on  https://www.mustangproject.org/einvoices/ and https://www.mustangproject.org/zugferd/  . Anyway, I went all in with the full apex URL config. 

http://www.zugferd.org for the time being I still need to figure out how to http://zugferd.org and https://www.zugferd.org .

Do you want to get involved? Apart from the optics and the idea to move into something more of a awesome-e-invoicing format there is at least one software missing (jes eür), I started writing a short "wanted poster" for each open source factur-x SDK i could get hold of and I need a place where I can publish that, we need help maintaining the corpus and the timeline and a colleague initiated the process to suggest to switch to something decent for the software directory (including proprietary) in the long run, i.e. https://github.com/research-software-directory/RSD-as-a-service ... there is just so much to do :-) And that does not even include your ideas.

kind regards
Jochen
